---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: pre-run | update repositories
    apt: update_cache=yes
    changed_when: False
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]

  tasks:
    - include: tasks/users.yml
    - include: tasks/directories.yml
    - include: tasks/packages.yml
    - include: tasks/python.yml
    - include: tasks/cron.yml
    - include: tasks/prepaks.yml
    - include: tasks/dotfiles.yml
    - include: tasks/x2gofiles.yml

  post_tasks:
  - name: cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]

  - name: autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]