---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

  - name: pre-run | update repositories (debian and ubuntu)
    apt: update_cache=yes
    changed_when: False
    when: ansible_os_family == "Debian"
    #when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]

  tasks:
    # - include: tasks/repo_unsigned.yml
    # - include: tasks/repo_signed.yml
#    - include: tasks/users.yml
    - include: tasks/directories.yml
    - include: tasks/packages.yml
    - include: tasks/python.yml
#    - include: tasks/cron.yml
    - include: tasks/flatpak.ymk
    - include: tasks/prepaks.yml
    - include: tasks/dotfiles.yml
    - include: tasks/configs.yml

  post_tasks:
  - name: post-run | cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_os_family == "Debian"
    #when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]

  - name: post-run | autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_os_family == "Debian"
    #when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]