---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: apt | Google Linux signing key
    apt_key: 
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
    state: present

  - name: apt | add Google Chrome repo
    apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: "google-chrome"
      state: present
#      update_cache: yes

  - name: apt | add Google Earth Pro repo 
    apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main"
      filename: "google-earth-pro"
      state: present
#      update_cache: yes

- name: apt | Add Microsoft APT key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == "Debian"

- name: apt | add Microsoft VScode repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    filename: "google-earth-pro"
    state: present
    update_cache: yes

- name: pre-run | update repositories (debian and ubuntu)
  apt: update_cache=yes
  changed_when: False
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]

  tasks:
    - include: tasks/users.yml
    - include: tasks/directories.yml
    - include: tasks/packages.yml
    - include: tasks/python.yml
#    - include: tasks/cron.yml
    - include: tasks/prepaks.yml
    - include: tasks/dotfiles.yml
    - include: tasks/configs.yml

  post_tasks:
  - name: post-run | cleanup package cache (debian and ubuntu)
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]

  - name: post-run | autoremove orphan packages (debian and ubuntu)
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu", "Linux Mint"]