- name: config | ensure flatpak repo are configured for system
  tags: workstation-packages
  command: flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: config | ensure flatpak repo are configured for --user
  tags: workstation-packages  
  command: flatpak remore-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Flatpaks
#- import_tasks: software/multimedia/spotify.yml
#- import_tasks: software/multimedia/vlc.yml
#- import_tasks: software/multimedia/noson.yml
#- import_tasks: software/multimedia/audacity.yml
#- import_tasks: software/graphics/darktable.yml
#- import_tasks: software/internet/discord.yml
#- import_tasks: software/graphics/inkscape.yml
#- import_tasks: software/graphics/gimp.yml
#- import_tasks: software/libreoffice.yml
#- import_tasks: software/internet/viber.yml
#- import_tasks: software/multimedia/handbrake.yml
#- import_tasks: software/bitwarden.yml
- import_tasks: software/multimedia/kid3.yml