- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - colordiff
      - curl
      - flatpak
      - gparted
      - htop
      - lsof
      - luckybackup
      - mc
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - python3
      - python3-pip
      - ranger
      - rsync
      - screen
      - sshfs
      - traceroute
      - ttf-mscorefonts-installer
      - wget
      - whois
      - x2goclient

- name: software packages | audio / video utilities
  tags: packages
  package:
    state: latest
    name:
      - ffmpeg
      - sox
      - mediainfo

- name: software packages | raspberry pi 
  tags: packages,pi
  package:
    state: latest
    name:
      - rpi-imager

- name: software | remove unneeded workstation packages on debian and ubuntu hosts
  tags: cleanup,packages,workstation-packages
  package:
    state: absent
    name:
      - gnote
      - thunderbird*
      - mosh
      - libreoffice