- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - bcompare
      - code
      - colordiff
      - curl
      - flatpak
      - gparted
      - google-chrome-stable
      - google-earth-pro-stable
      - htop
      #- lsof
      - luckybackup
      - mc
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - python3
      - python3-pip
      #- ranger
      - rsync
      #- screen
      - sshfs
      - terminator
      - tmux
      - traceroute
      - ttf-mscorefonts-installer
      - wget
      - whois
      - x2goclient

- name: software packages | audio / video utilities
  tags: packages
  package:
    state: latest
    name:
      - ffmpeg
      - sox
      - mediainfo

- name: software | remove unneeded workstation packages on debian and ubuntu hosts
  tags: cleanup,packages,workstation-packages
  package:
    state: absent
    name:
      - gnote
      - thunderbird*
      - mosh
      - libreoffice*

- name: config | ensure flatpak repo are configured
  tags: workstation-packages
  command: flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
