- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - colordiff
      - curl
      - gparted
      - htop
      - lsof
      - mc
      - mosh
      - ncdu
      - neofetch
      - net-tools
      - nmap
      - ranger
      - rsync
      - screen
      - sshfs
      - traceroute
      - wget
      - whois

- name: software | remove unneeded workstation packages on debian and ubuntu hosts
  tags: cleanup,packages,workstation-packages
  package:
    state: absent
    name:
      - gnote
      - thunderbird*
