# Add additional repositories 
# Google Chrome
# Google Earth
# Microsoft VS Code
# Scooter Software Beyond Compare

- name: apt | Google Linux signing key
  apt_key: 
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub 
    state: present
  when: ansible_os_family == "Debian"

- name: apt | add Google Chrome repo
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
  when: ansible_os_family == "Debian"

- name: apt | add Google Earth Pro repo 
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/earth/deb/ stable main"
    filename: "google-earth-pro"
    state: present
  when: ansible_os_family == "Debian"

- name: apt | Add Microsoft signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_os_family == "Debian"

- name: apt | add Microsoft VScode repo
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    filename: "vscode"
    state: present
  when: ansible_os_family == "Debian"

- name: apt | Add Scooter Software signing key
  apt_key:
    url: http://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware
    state: present
  when: ansible_os_family == "Debian"

- name: apt | add Beyond Compare repo
  apt_repository:
    repo: "deb https://www.scootersoftware.com/ bcompare4 non-free"
    filename: "scootersoftware"
    state: present
  when: ansible_os_family == "Debian"

- name: Add ulauncher repository
  apt_repository: 
    repo: "ppa:agornostal/ulauncher"
    state: present
  when: ansible_os_family == "Debian"
