- name: software | unofficial sonos controller | copy launcher
  tags: apps,appimage,software,unofficial-sonos
  copy:
    src: desktop/unofficial-sonos.desktop
    dest: /home/martin/.local/share/applications/unofficial-sonos.desktop
    owner: martin
    group: martin
    mode: 0700

- name: software | unofficial sonos controller | install package
  get_url:
    url: https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/download/v0.2.7/sonos-controller-unofficial-0.2.7.AppImage
    dest: /home/martin/bin/unofficialsonos.app
    mode: '0700'
    owner: martin
    group: martin

# would be useful to pull in the latest version
# curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/pascalopitz/unoffical-sonos-controller-for-linux/releases/latest
