- name: software | unofficial sonos controller | copy launcher
  tags: apps,appimage,software,unofficial-sonos
  copy:
    src: desktop/unofficial-sonos.desktop
    dest: /home/martin/.local/share/applications/unofficial-sonos.desktop
    owner: martin
    group: martin
    mode: 0700

- name: software | unofficial sonos controller | install package
  get_url:
    url: https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/download/v0.2.8/sonos-controller-unofficial-0.2.8.AppImage
    dest: /home/martin/bin/unofficialsonos.app
    mode: '0700'
    owner: martin
    group: martin
