- name: Software  | Unofficial Sonos Controller | Get Latest version
  tags: apps,appimage,software,unofficial-sonos
  github_release:
    user: pascalopitz
    repo: unoffical-sonos-controller-for-linux
    action: latest_release
  register: release

- name: "Unofficial Sonos Controller | Download and install"
  get_url:
    url: "https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/download/v{{ release.tag[1:] }}/sonos-controller-unofficial-{{ release.tag[1:] }}.AppImage"
    dest: /home/martin/bin/unofficialsonos.app
    mode: '0700'
    owner: martin
    group: martin

- name: software | unofficial sonos controller | copy launcher
  tags: apps,appimage,software,unofficial-sonos
  copy:
    src: desktop/unofficial-sonos.desktop
    dest: /home/martin/.local/share/applications/unofficial-sonos.desktop
    owner: martin
    group: martin
    mode: 0700
