- name: software | vlc | install package
  tags: packages,flatpak,vlc,workstation-packages
  become_user: martin
  flatpak:
    name: org.videolan.VLC
    state: present

#  when:
#    - vlc is defined
#    - vlc == true
